spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        payment: payment_channel


server:
  port: 9080

logging:
  level:
    root: info

currency:
  exchange:
    url: https://openexchangerates.org
    appId: ca800d6c1f28496a9461bd842d20b919
    commission: 1

clear-scheduler:
  cron: "0 */10 * * * *" # every 5 minute
  auto-clear-delay-amount: 15 # in minutes

account-service:
  host: localhost
  port: 8090
  repeatable-delay: 3000